#!/bin/bash

# Run hml hooks related commands.

Lsb_release() {
    local file=/etc/lsb-release

    if [ -z "$(grep "^DISTRIB_CODENAME=" $file)" ] ; then
        # add missing DISTRIB_CODENAME=
        echo "DISTRIB_CODENAME=rolling" >> $file
    fi
    sed -i $file \
        -e 's|^DISTRIB_ID=.*$|DISTRIB_ID=hml|' \
        -e 's|^DISTRIB_CODENAME=.*$|DISTRIB_CODENAME=rolling|' \
        -e 's|^DISTRIB_DESCRIPTION=.*$|DISTRIB_DESCRIPTION=\"Hatsune Miku Linux\"|'
}

Os_release() {
    local file=/usr/lib/os-release
    local hmlfile=/usr/lib/hml-release

    # Get URLs from the EndeavourOS web site!
    sed -i $file \
        -e 's|^NAME=.*$|NAME=\"Hatsune Miku Linux\"|' \
        -e 's|^PRETTY_NAME=.*$|PRETTY_NAME=\"Hatsune Miku Linux\"|' \
        -e "s|^LOGO=.*$|LOGO=hml-logo|" \
        -e "s|^ID=.*$|ID=hml|" \
        -e "s|^ID_LIKE=.*$|ID_LIKE=arch|"

    if [ -z "$(grep "^ID_LIKE=" $file)" ] && [ -n "$(grep "^ID=" $file)" ] ; then
        # add missing ID_LIKE=
        sed -i $file -e '/^ID=/a \ID_LIKE=arch'
    fi
    if [ -r $hmlfile ] ; then
        # fix BUILD_ID for EndeavourOS
        local buildid="$(grep "^VERSION=" $hmlfile | awk '{print $1}' | cut -d '=' -f 2)"
        sed -i $file -e "s|^BUILD_ID=.*$|BUILD_ID=$buildid|"
    fi
}

Issues() {
    sed -i 's|Arch|Hatsune\ Miku|g' /etc/issue /usr/share/factory/etc/issue
}

Pixmaps() {
	## Remove Arch Linux artworks
	imgs=('archlinux-logo.png'
		  'archlinux-logo.svg'
		  'archlinux-logo-text.svg'
		  'archlinux-logo-text-dark.svg'
		  'archlinux.png'
		  'archlinux.svg')
	
	for img in "${imgs[@]}"; do
		if [[ -e /usr/share/pixmaps/"$img" ]]; then 
			rm -rf /usr/share/pixmaps/"$img"
		fi
	done	
}

Main()
{
    local hookname="$1"

    case "$hookname" in
        os-release)  Os_release ;;
        lsb-release) Lsb_release ;;
        "")          Os_release
                     Lsb_release
                     Issues
                     ;;
    esac
}

Main "$@"
